 import request from 'supertest'
 import { randomUUID } from 'node:crypto'
 import { app } from '../helpers/testServer.js'
 import { registerUser } from '../helpers/authHelper.js'
 import { createChat } from '../helpers/chatHelper.js'
 import { prisma, resetDatabase, disconnectPrisma } from '../helpers/prismaTestClient.js'

beforeEach(async () => {
  await resetDatabase()
})

afterAll(async () => {
  await resetDatabase()
  await disconnectPrisma()
})

describe('GET /chats', () => {
  it('rejects requests with no auth token with 401', async () => {
    const res = await request(app).get('/chats')
    expect(res.status).toBe(401)
  })
  it('returns an empty list when the user has no chats', async () => {
    const dragon = await registerUser()
    const res = await request(app)
      .get('/chats')
      .set('Authorization', `Bearer ${dragon.token}`)
    expect(res.status).toBe(200)
    expect(res.body.success).toBe(true)
    expect(res.body.chats).toEqual([])
  })
  it('returns a DM with the other member\'s username as its name', async () => {
    const dragon = await registerUser()
    const lucky = await registerUser()
    const chat = await createChat({ token: dragon.token, memberIds: [lucky.userId] })
    const res = await request(app)
      .get('/chats')
      .set('Authorization', `Bearer ${dragon.token}`)
    expect(res.status).toBe(200)
    expect(res.body.chats).toHaveLength(1)
    expect(res.body.chats[0]).toMatchObject({
      id: chat.id,
      name: lucky.username,
      isGroup: false,
      lastMessage: null
    })
  })
  it('does not return chats the user is not a member of', async () => {
    const dragon = await registerUser()
    const lucky = await registerUser()
    const jasmine = await registerUser()
    await createChat({ token: dragon.token, memberIds: [lucky.userId] })
    const res = await request(app)
      .get('/chats')
      .set('Authorization', `Bearer ${jasmine.token}`)
    expect(res.status).toBe(200)
    expect(res.body.chats).toEqual([])
  })
})

describe('POST /chats/newChat', () => {
  it('rejects requests with no auth token with 401', async () => {
    const res = await request(app)
      .post('/chats/newChat')
      .send({ members: [randomUUID()] })
    expect(res.status).toBe(401)
  })
  it('rejects an empty members array with 400', async () => {
    const dragon = await registerUser()
    const res = await request(app)
      .post('/chats/newChat')
      .set('Authorization', `Bearer ${dragon.token}`)
      .send({ members: [] })
    expect(res.status).toBe(400)
    expect(res.body.success).toBe(false)
  })
  it('rejects a malformed (non-UUID) member id with 400 at the validation layer', async () => {
    const lucky = await registerUser()
    const res = await request(app)
      .post('/chats/newChat')
      .set('Authorization', `Bearer ${lucky.token}`)
      .send({ members: ['not-a-valid-uuid'] })
    expect(res.status).toBe(400)
    expect(res.body.success).toBe(false)
  })
  it('rejects duplicate member ids in the same array with 400', async () => {
    const dragon = await registerUser()
    const lucky = await registerUser()
    const res = await request(app)
      .post('/chats/newChat')
      .set('Authorization', `Bearer ${dragon.token}`)
      .send({ members: [lucky.userId, lucky.userId] })
    expect(res.status).toBe(400)
    expect(res.body.success).toBe(false)
  })
  it('rejects a well-formed but non-existent member id with 400 at the controller layer', async () => {
    const lucky = await registerUser()
    const nonExistentId = randomUUID()
    const res = await request(app)
      .post('/chats/newChat')
      .set('Authorization', `Bearer ${lucky.token}`)
      .send({ members: [nonExistentId] })
    expect(res.status).toBe(400)
    expect(res.body.success).toBe(false)
  })
  it('creates a DM when the total member count is exactly 2', async () => {
    const dragon = await registerUser()
    const lucky = await registerUser()
    const res = await request(app)
      .post('/chats/newChat')
      .set('Authorization', `Bearer ${dragon.token}`)
      .send({ members: [lucky.userId] })
    expect(res.status).toBe(200)
    expect(res.body.success).toBe(true)
    expect(res.body.chat.isGroup).toBe(false)
    expect(res.body.chat.members).toHaveLength(2)
  })
  it('returns the existing DM instead of creating a duplicate', async () => {
    const dragon = await registerUser()
    const jasmine = await registerUser()
    const firstChat = await createChat({ token: dragon.token, memberIds: [jasmine.userId] })
    const res = await request(app)
      .post('/chats/newChat')
      .set('Authorization', `Bearer ${dragon.token}`)
      .send({ members: [jasmine.userId] })
    expect(res.status).toBe(200)
    expect(res.body.message).toBe('Direct message already exists.')
    expect(res.body.chat.id).toBe(firstChat.id)
  })
  it('creates a group chat when the total member count is more than 2', async () => {
    const dragon = await registerUser()
    const lucky = await registerUser()
    const jasmine = await registerUser()
    const res = await request(app)
      .post('/chats/newChat')
      .set('Authorization', `Bearer ${dragon.token}`)
      .send({ members: [lucky.userId, jasmine.userId], name: 'Summer Holiday' })
    expect(res.status).toBe(200)
    expect(res.body.chat.isGroup).toBe(true)
    expect(res.body.chat.name).toBe('Summer Holiday')
    expect(res.body.chat.members).toHaveLength(3)
  })
  it('rejects a second group chat with the same name from the same creator with 409', async () => {
    const dragon = await registerUser()
    const lucky = await registerUser()
    const jasmine = await registerUser()
    const warrior = await registerUser()
    await createChat({
      token: dragon.token,
      memberIds: [lucky.userId, jasmine.userId],
      name: 'Summer Holiday'
    })
    const res = await request(app)
      .post('/chats/newChat')
      .set('Authorization', `Bearer ${dragon.token}`)
      .send({ members: [jasmine.userId, warrior.userId], name: 'Summer Holiday' })
    expect(res.status).toBe(409)
    expect(res.body.success).toBe(false)
  })
})

describe('PATCH /chats/:chatId/name', () => {
  it('rejects requests with no auth token with 401', async () => {
    const jasmine = await registerUser()
    const warrior = await registerUser()
    const chat = await createChat({ token: jasmine.token, memberIds: [warrior.userId] })
    const res = await request(app)
      .patch(`/chats/${chat.id}/name`)
      .send({ name: 'New Name' })
    expect(res.status).toBe(401)
  })
  it('rejects a non-admin member with 403', async () => {
    const jasmine = await registerUser()
    const warrior = await registerUser()
    const chat = await createChat({ token: jasmine.token, memberIds: [warrior.userId] })
    const res = await request(app)
      .patch(`/chats/${chat.id}/name`)
      .set('Authorization', `Bearer ${warrior.token}`)
      .send({ name: 'New Name' })
    expect(res.status).toBe(403)
    expect(res.body.success).toBe(false)
    expect(res.body.message).toBe('Admin access required.')
  })
  it('rejects an invalid name with 400', async () => {
    const jasmine = await registerUser()
    const warrior = await registerUser()
    const chat = await createChat({ token: jasmine.token, memberIds: [warrior.userId] })
    const res = await request(app)
      .patch(`/chats/${chat.id}/name`)
      .set('Authorization', `Bearer ${jasmine.token}`)
      .send({ name: 'Hi' })
    expect(res.status).toBe(400)
    expect(res.body.success).toBe(false)
  })
  it('renames the chat when requesting member is admin', async () => {
    const jasmine = await registerUser()
    const warrior = await registerUser()
    const chat = await createChat({ token: jasmine.token, memberIds: [warrior.userId] })
    const res = await request(app)
      .patch(`/chats/${chat.id}/name`)
      .set('Authorization', `Bearer ${jasmine.token}`)
      .send({ name: 'Renamed Chat' })
    expect(res.status).toBe(200)
    expect(res.body.success).toBe(true)
    expect(res.body.chat.name).toBe('Renamed Chat')
    const stored = await prisma.chat.findUnique({ where: { id: chat.id } })
    expect(stored?.name).toBe('Renamed Chat')
  })
})

describe('DELETE /chats/:chatId', () => {
  it('rejects requests with no auth token with 401', async () => {
    const jasmine = await registerUser()
    const warrior = await registerUser()
    const chat = await createChat({ token: jasmine.token, memberIds: [warrior.userId] })
    const res = await request(app).delete(`/chats/${chat.id}`)
    expect(res.status).toBe(401)
  })
  it('rejects a non-admin member with 403', async () => {
    const jasmine = await registerUser()
    const warrior = await registerUser()
    const chat = await createChat({ token: jasmine.token, memberIds: [warrior.userId] })
    const res = await request(app)
      .delete(`/chats/${chat.id}`)
      .set('Authorization', `Bearer ${warrior.token}`)
    expect(res.status).toBe(403)
    expect(res.body.success).toBe(false)
    expect(res.body.message).toBe('Admin access required.')
  })
  it('deletes the chat when requesting member is admin', async () => {
    const jasmine = await registerUser()
    const warrior = await registerUser()
    const chat = await createChat({ token: jasmine.token, memberIds: [warrior.userId] })
    const res = await request(app)
      .delete(`/chats/${chat.id}`)
      .set('Authorization', `Bearer ${jasmine.token}`)
    expect(res.status).toBe(200)
    expect(res.body.success).toBe(true)
    const stored = await prisma.chat.findUnique({ where: { id: chat.id } })
    expect(stored).toBeNull()
  })
})

describe('POST /chats/:chatId/members', () => {
  it('rejects requests with no auth token with 401', async () => {
    const lucky = await registerUser()
    const jasmine = await registerUser()
    const warrior = await registerUser()
    const chat = await createChat({ token: lucky.token, memberIds: [jasmine.userId] })
    const res = await request(app)
      .post(`/chats/${chat.id}/members`)
      .send({ userId: warrior.userId })
    expect(res.status).toBe(401)
  })
  it('rejects a non-admin member with 403', async () => {
    const lucky = await registerUser()
    const jasmine = await registerUser()
    const warrior = await registerUser()
    const chat = await createChat({ token: lucky.token, memberIds: [jasmine.userId] })
    const res = await request(app)
      .post(`/chats/${chat.id}/members`)
      .set('Authorization', `Bearer ${jasmine.token}`)
      .send({ userId: warrior.userId })
    expect(res.status).toBe(403)
    expect(res.body.success).toBe(false)
    expect(res.body.message).toBe('Admin access required.')
  })
  it('rejects a non-existent userId with 404', async () => {
    const lucky = await registerUser()
    const jasmine = await registerUser()
    const chat = await createChat({ token: lucky.token, memberIds: [jasmine.userId] })
    const res = await request(app)
      .post(`/chats/${chat.id}/members`)
      .set('Authorization', `Bearer ${lucky.token}`)
      .send({ userId: randomUUID() })
    expect(res.status).toBe(404)
    expect(res.body.success).toBe(false)
  })
  it('rejects a user who is already a member with 409', async () => {
    const lucky = await registerUser()
    const jasmine = await registerUser()
    const chat = await createChat({ token: lucky.token, memberIds: [jasmine.userId] })
    const res = await request(app)
      .post(`/chats/${chat.id}/members`)
      .set('Authorization', `Bearer ${lucky.token}`)
      .send({ userId: jasmine.userId })
    expect(res.status).toBe(409)
    expect(res.body.success).toBe(false)
  })
  it('adds a new member when requesting member is admin', async () => {
    const lucky = await registerUser()
    const jasmine = await registerUser()
    const warrior = await registerUser()
    const chat = await createChat({ token: lucky.token, memberIds: [jasmine.userId] })
    const res = await request(app)
      .post(`/chats/${chat.id}/members`)
      .set('Authorization', `Bearer ${lucky.token}`)
      .send({ userId: warrior.userId })
    expect(res.status).toBe(200)
    expect(res.body.success).toBe(true)
    const stored = await prisma.chatMember.findUnique({
      where: { userId_chatId: { userId: warrior.userId, chatId: chat.id } }
    })
    expect(stored).not.toBeNull()
    expect(stored?.role).toBe('MEMBER')
  })
})

describe('PATCH /chats/:chatId/members/:userId/role', () => {
  it('rejects requests with no auth token with 401', async () => {
    const lucky = await registerUser()
    const jasmine = await registerUser()
    const chat = await createChat({ token: lucky.token, memberIds: [jasmine.userId] })
    const res = await request(app).patch(`/chats/${chat.id}/members/${jasmine.userId}/role`)
    expect(res.status).toBe(401)
  })
  it('rejects a non-admin member with 403', async () => {
    const lucky = await registerUser()
    const jasmine = await registerUser()
    const chat = await createChat({ token: lucky.token, memberIds: [jasmine.userId] })
    const res = await request(app)
      .patch(`/chats/${chat.id}/members/${jasmine.userId}/role`)
      .set('Authorization', `Bearer ${jasmine.token}`)
    expect(res.status).toBe(403)
    expect(res.body.success).toBe(false)
    expect(res.body.message).toBe('Admin access required.')
  })
  it('rejects a userId that is not a member of this chat with 404', async () => {
    const lucky = await registerUser()
    const jasmine = await registerUser()
    const warrior = await registerUser()
    const chat = await createChat({ token: lucky.token, memberIds: [jasmine.userId] })
    const res = await request(app)
      .patch(`/chats/${chat.id}/members/${warrior.userId}/role`)
      .set('Authorization', `Bearer ${lucky.token}`)
    expect(res.status).toBe(404)
    expect(res.body.success).toBe(false)
  })
  it('rejects demoting the only admin with 400', async () => {
    const lucky = await registerUser()
    const jasmine = await registerUser()
    const chat = await createChat({ token: lucky.token, memberIds: [jasmine.userId] })
    const res = await request(app)
      .patch(`/chats/${chat.id}/members/${lucky.userId}/role`)
      .set('Authorization', `Bearer ${lucky.token}`)
    expect(res.status).toBe(400)
    expect(res.body.success).toBe(false)
  })
  it('promotes a member to admin when requesting member is admin', async () => {
    const lucky = await registerUser()
    const jasmine = await registerUser()
    const chat = await createChat({ token: lucky.token, memberIds: [jasmine.userId] })
    const res = await request(app)
      .patch(`/chats/${chat.id}/members/${jasmine.userId}/role`)
      .set('Authorization', `Bearer ${lucky.token}`)
    expect(res.status).toBe(200)
    expect(res.body.member.role).toBe('ADMIN')
  })
  it('demotes an admin back to member when another admin remains', async () => {
    const lucky = await registerUser()
    const jasmine = await registerUser()
    const chat = await createChat({ token: lucky.token, memberIds: [jasmine.userId] })
    await request(app)
      .patch(`/chats/${chat.id}/members/${jasmine.userId}/role`)
      .set('Authorization', `Bearer ${lucky.token}`)
    const res = await request(app)
      .patch(`/chats/${chat.id}/members/${lucky.userId}/role`)
      .set('Authorization', `Bearer ${lucky.token}`)
    expect(res.status).toBe(200)
    expect(res.body.member.role).toBe('MEMBER')
  })
})

describe('DELETE /chats/:chatId/members/:userId', () => {
  it('rejects requests with no auth token with 401', async () => {
    const jasmine = await registerUser()
    const warrior = await registerUser()
    const chat = await createChat({ token: jasmine.token, memberIds: [warrior.userId] })
    const res = await request(app).delete(`/chats/${chat.id}/members/${warrior.userId}`)
    expect(res.status).toBe(401)
  })
  it('rejects a user who is not a member of the chat with 403', async () => {
    const lucky = await registerUser()
    const jasmine = await registerUser()
    const warrior = await registerUser()
    const chat = await createChat({ token: lucky.token, memberIds: [jasmine.userId] })
    const res = await request(app)
      .delete(`/chats/${chat.id}/members/${jasmine.userId}`)
      .set('Authorization', `Bearer ${warrior.token}`)
    expect(res.status).toBe(403)
    expect(res.body.success).toBe(false)
    expect(res.body.message).toBe('Not a member of this chat.')
  })
  it('rejects a member who is not an admin of the chat with 403', async () => {
    const jasmine = await registerUser()
    const warrior = await registerUser()
    const chat = await createChat({ token: jasmine.token, memberIds: [warrior.userId] })
    const res = await request(app)
      .delete(`/chats/${chat.id}/members/${jasmine.userId}`)
      .set('Authorization', `Bearer ${warrior.token}`)
    expect(res.status).toBe(403)
    expect(res.body.success).toBe(false)
    expect(res.body.message).toBe('Admin access required.')
  })
  it('rejects the only admin removing themselves with 400', async () => {
    const jasmine = await registerUser()
    const warrior = await registerUser()
    const chat = await createChat({ token: jasmine.token, memberIds: [warrior.userId] })
    const res = await request(app)
      .delete(`/chats/${chat.id}/members/${jasmine.userId}`)
      .set('Authorization', `Bearer ${jasmine.token}`)
    expect(res.status).toBe(400)
    expect(res.body.success).toBe(false)
  })
  it('removes another member when requesting member is admin', async () => {
    const jasmine = await registerUser()
    const warrior = await registerUser()
    const chat = await createChat({ token: jasmine.token, memberIds: [warrior.userId] })
    const res = await request(app)
      .delete(`/chats/${chat.id}/members/${warrior.userId}`)
      .set('Authorization', `Bearer ${jasmine.token}`)
    expect(res.status).toBe(200)
    expect(res.body.success).toBe(true)
    const stored = await prisma.chatMember.findUnique({
      where: { userId_chatId: { userId: warrior.userId, chatId: chat.id } }
    })
    expect(stored).toBeNull()
  })
  it('rejects a userId that is not a member of this chat with 404', async () => {
    const lucky = await registerUser()
    const jasmine = await registerUser()
    const warrior = await registerUser()
    const chat = await createChat({ token: lucky.token, memberIds: [jasmine.userId] })
    const res = await request(app)
      .delete(`/chats/${chat.id}/members/${warrior.userId}`)
      .set('Authorization', `Bearer ${lucky.token}`)
    expect(res.status).toBe(404)
    expect(res.body.success).toBe(false)
  })
})
